MANUX_STACK_SEG_16=0x9000
MANUX_CONFIG=True
MANUX_PAGINATION=True
MANUX_CLAVIER=True
MANUX_KERNEL_TASK_TSS_IND=0x20
MANUX_NB_MAX_FICHIERS=4
MANUX_ELF_HEADER_SIZE=0x80
MANUX_FREQUENCE_TIMER=100
MANUX_TAILLE_PAGE=0x1000
MANUX_APPELS_SYSTEME=True
MANUX_CONSOLES_VIRTUELLES=True
MANUX_JOURNAL=True
MANUX_NB_SECT_RAMDISK=0x2
MANUX_TACHES=True
MANUX_SEGMENT_TRANSIT_RAMDISK=0x4000
MANUX_GESTION_MEMOIRE=True
MANUX_INIT_START_ADDRESS=0x1000
MANUX_PREMIER_SECT_RAMDISK=0x10
MANUX_ADRESSE_DEBUT_TAS=0x1000000
MANUX_KERNEL_START_ADDRESS=0x20000
MANUX_CODE_SEG_SEL=0x08
MANUX_PREEMPTIF=True
MANUX_DATA_SEG_SEL=0x10
MANUX_AFFECTATION_PAGES=0x1000
MANUX_portDonneesClavier=0x60
MANUX_NOMBRE_PAGES_SYSTEME=0x800
MANUX_ADRESSE_ECRAN=0xb8000
MANUX_NB_SECT_INIT=0x02
MANUX_portCmdClavier=0x64
