# Fichier généré automatiquement, ne pas modifier
TAILLE_PAGE = 0x1000
NOMBRE_PAGES_SYSTEME = 0x800
KERNEL_START_ADDRESS = 0x20000
INIT_START_ADDRESS = 0x1000
MANUX_STACK_SEG_16 = 0x9000
ELF_HEADER_SIZE = 0x80
ADRESSE_ECRAN = 0xb8000
NB_SECT_INIT = 0x2
NB_SECT_RAMDISK = 0x2
SEGMENT_TRANSIT_RAMDISK = 0x4000
PREMIER_SECT_RAMDISK = 0x10
portDonneesClavier = 0x60
portCmdClavier = 0x64
