#      Définition des principaux paramètres de ManuX
#---------------------------------------------------
MANUX_TEXT_SEGMENT   = 20000

# Définition des indices de descripteurs dans la GDT
MANUX_CODE_SEG_SEL   = 0x08
MANUX_DATA_SEG_SEL   = 0x10
MANUX_KERNEL_TASK_TSS_IND = 0x20

