#define MANUX_NB_HANDLER_PAR_IRQ 4
#define MANUX_NB_IRQ 16
#define MANUX_CONSOLE 
#define MANUX_REGISTRE 
#define MANUX_CONFIG 
#define MANUX_PAGINATION 
#define MANUX_INIT_MAGIC 0x01c0ffee
#define MANUX_TAILLE_PAGE 0x1000
#define MANUX_NB_EXCEPTIONS 32
#define MANUX_HANDLER_IRQ i8259aGestionIRQ
#define MANUX_ADRESSE_IDT 0x41000
#define MANUX_INT_BASE_IRQ MANUX_NB_EXCEPTIONS
#define MANUX_PIC INTEL_8259A
#define MANUX_INT_AUDIT 
#define MANUX_PIC_INIT i8259aInit
#define MANUX_KMALLOC kmalloc-zs
#define MANUX_LIBI386 
#define MANUX_TAILLE_PILE 16384
#define MANUX_IDT_NB_PAGES 1
#define MANUX_GESTION_MEMOIRE 
#define MANUX_NB_CYCLES_CALIBRAGE MANUX_FREQUENCE_HORLOGE
#define MANUX_BOOT_START_ADDRESS 0x7c00
#define MANUX_ELF_HEADER_SIZE 0x80
#define MANUX_ADRESSE_BIOS 0x80000
#define MANUX_INIT_START_ADDRESS 0x7e00
#define MANUX_PRINTK 
#define MANUX_CONSOLE_MAJEUR 0
#define MANUX_KERNEL_START_ADDRESS 0x20000
#define MANUX_NB_SECT_INIT 0x02
#define MANUX_FREQUENCE_HORLOGE 100
#define MANUX_AFFECTATION_PAGES 0x1000
#define MANUX_STACK_SEG_16 0x9000
#define MANUX_ADRESSE_GDT 0x42000
#define MANUX_GDT_NB_PAGES 1
#define MANUX_NB_INTERRUPTIONS 256
#define MANUX_NOMBRE_PAGES_SYSTEME 0x800
#define MANUX_ADRESSE_ECRAN 0xb8000
#define MANUX_KMALLOC_STAT 
#define MANUX_BOOTLOADER 
#define MANUX_FICHIER_MAIN main-debugmask-dyn
#define MANUX_BIOS_NB_PAGES 0x80
